FROM openjdk:21-jdk-slim

# Setup envs
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME
ARG JDBC_STAGING_DATABASE_USERNAME
ARG JDBC_STAGING_DATABASE_URL
ARG JDBC_STAGING_DATABASE_URL

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME}
ENV JDBC_STAGING_DATABASE_PASSWORD ${JDBC_STAGING_DATABASE_PASSWORD}
ENV JDBC_STAGING_DATABASE_URL ${JDBC_STAGING_DATABASE_URL}
ENV JDBC_STAGING_DATABASE_USERNAME ${JDBC_STAGING_DATABASE_USERNAME}

WORKDIR /app
COPY ./app/target/authentication-0.1.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
